<?php

namespace BackendBundle\Repository;

/**
 * FleurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FleurRepository extends \Doctrine\ORM\EntityRepository
{
}
